language: node_js
node_js:
  - node
  - 6
  - 5
  - 4
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm t
after_success:
  - npm run semantic-release
